sudo: required

language: android
jdk: oraclejdk8

env:
 global:
    - ANDROID_TARGET1=android-21
    - ANDROID_TARGET2=android-15
    - ANDROID_ABI=armeabi-v7a

android:
  components:
    - tools
    - tools
    - platform-tools
    - android-24
    - build-tools-24.0.1
    - extra-android-m2repository
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET1}
    - sys-img-${ANDROID_ABI}-${ANDROID_TARGET2}

before_install:
 - chmod +x gradlew
 - pip install --user codecov

script:
    # Create two emulator avds.
  - echo no | android create avd --force -n test1 -t ${ANDROID_TARGET1} --abi ${ANDROID_ABI}
  - echo no | android create avd --force -n test2 -t ${ANDROID_TARGET2} --abi ${ANDROID_ABI}

    # Start the first emulator.
  - emulator -avd test1 -no-skin -no-audio -no-window &
  - sh scripts/wait-for-emulator.sh

    # Just to check whether the device is seen by ADB.
  - "adb devices"

    # Unlock the device.
  - adb -s emulator-5554 shell input keyevent 82 &

    # Run the script.
  - sh scripts/script.sh

    # Move the coverage report from the first device.
  - sh scripts/move-coverage-report.sh

    # Kill the first emulator.
  - sh scripts/kill-first-emulator.sh

    # Start the second emulator.
  - emulator -avd test2 -no-skin -no-audio -no-window &
  - sh scripts/wait-for-emulator.sh

    # Just to check whether the device is seen by ADB.
  - "adb devices"

    # Unlock the device.
  - adb -s emulator-5554 shell input keyevent 82 &

    # Run tests on another device.
  - sh scripts/script-just-ui.sh

notifications:
  email: true

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock

cache:
  directories:
    - $HOME/.m2
    - $HOME/.gradle
    - $HOME/.gradle/caches/
    - $HOME/.gradle/wrapper/
    
after_success:
- codecov
